name: Envioments

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to DEV"

  STAGE:
    runs-on: ubuntu-latest
    environment: STAGE
    needs: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to Stage"

  PROD:
    runs-on: ubuntu-latest
    environment: PROD
    needs: STAGE
    steps:
      - name: Deploy
        run: echo "Deployed to Prod"  