name: Envioments

on:
  workflow_dispatch:

jobs:
  DEV:
    runs-on: ubuntu-latest
    enviroment: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to DEV"

  STAGE:
    runs-on: ubuntu-latest
    enviroment: STAGE
    needs: DEV
    steps:
      - name: Deploy
        run: echo "Deployed to Stage"

  PROD:
    runs-on: ubuntu-latest
    enviroment: PROD
    needs: STAGE
    steps:
      - name: Deploy
        run: echo "Deployed to Prod"  